---
# tasks file for Tomcat
  - name: Install Java
    yum:
      name: java
      state: present

  - name: Install Tomcat 8
    get_url:
      url: "{{ tomcat_url }}"
      dest: "{{ tomcat_home }}"

  - name: Unarchive Tomcat
    unarchive:
      src: "{{ tomcat_home }}/apache-tomcat-8.0.32.tar.gz"
      dest: "{{ tomcat_home }}"
      remote_src: yes

  - name: create symbolic link for tomcat 8
    file:
      src: "{{ tomcat_home }}/apache-tomcat-8.0.32"
      dest: "{{ tomcat_home }}/tomcat8"
      owner: root
      group: root
      state: link

  - name: start tomcat8
    shell: nohup /opt/tomcat8/bin/startup.sh &
